### PR TITLE
only reveal file in the sidebar if the sidebar is already open

### PR DESCRIPTION
**Pull request by mattsawyer77**

### CODE REVIEW

**Comment by mattsawyer77** [comment]
Forgot to mention, this would resolve #2

**Comment by DeanNonatomic** [comment]
Fantastic stuff! Merged in :)

Thanks

**Comment by mattsawyer77** [comment]
thanks for the quick merge! do you mind bumping your apm version now to disseminate the change?

**Comment by DeanNonatomic** [comment]
Done, now at v0.5.0 :)

**Pull request merged**
